/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as RegisterRouteImport } from './app/register'
import { Route as ProjectsRouteImport } from './app/projects'
import { Route as PRouteImport } from './app/p'
import { Route as ModelsRouteImport } from './app/models'
import { Route as MapsRouteImport } from './app/maps'
import { Route as LoginRouteImport } from './app/login'
import { Route as ExamplesRouteImport } from './app/examples'
import { Route as DataRouteImport } from './app/data'
import { Route as CustomizeRouteImport } from './app/customize'
import { Route as CompaniesRouteImport } from './app/companies'
import { Route as IndexRouteImport } from './app/index'
import { Route as ProjectsIndexRouteImport } from './app/projects/index'
import { Route as ModelsIndexRouteImport } from './app/models/index'
import { Route as ExamplesIndexRouteImport } from './app/examples/index'
import { Route as DataIndexRouteImport } from './app/data/index'
import { Route as CompaniesIndexRouteImport } from './app/companies/index'
import { Route as PShareIdRouteImport } from './app/p/$shareId'
import { Route as ExamplesBasicRouteImport } from './app/examples/basic'
import { Route as Examples3dRouteImport } from './app/examples/3d'
import { Route as DataIdRouteImport } from './app/data/$id'
import { Route as CompaniesIdRouteImport } from './app/companies/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PRoute = PRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRoute,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesRoute,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const PShareIdRoute = PShareIdRouteImport.update({
  id: '/$shareId',
  path: '/$shareId',
  getParentRoute: () => PRoute,
} as any)
const ExamplesBasicRoute = ExamplesBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => ExamplesRoute,
} as any)
const Examples3dRoute = Examples3dRouteImport.update({
  id: '/3d',
  path: '/3d',
  getParentRoute: () => ExamplesRoute,
} as any)
const DataIdRoute = DataIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DataRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/data': typeof DataRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/models': typeof ModelsRouteWithChildren
  '/p': typeof PRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/data/$id': typeof DataIdRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/p/$shareId': typeof PShareIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/data/': typeof DataIndexRoute
  '/examples/': typeof ExamplesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customize': typeof CustomizeRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/p': typeof PRouteWithChildren
  '/register': typeof RegisterRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/data/$id': typeof DataIdRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/p/$shareId': typeof PShareIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/data': typeof DataIndexRoute
  '/examples': typeof ExamplesIndexRoute
  '/models': typeof ModelsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/customize': typeof CustomizeRoute
  '/data': typeof DataRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/models': typeof ModelsRouteWithChildren
  '/p': typeof PRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/data/$id': typeof DataIdRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/p/$shareId': typeof PShareIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/data/': typeof DataIndexRoute
  '/examples/': typeof ExamplesIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/customize'
    | '/data'
    | '/examples'
    | '/login'
    | '/maps'
    | '/models'
    | '/p'
    | '/projects'
    | '/register'
    | '/companies/$id'
    | '/data/$id'
    | '/examples/3d'
    | '/examples/basic'
    | '/p/$shareId'
    | '/companies/'
    | '/data/'
    | '/examples/'
    | '/models/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customize'
    | '/login'
    | '/maps'
    | '/p'
    | '/register'
    | '/companies/$id'
    | '/data/$id'
    | '/examples/3d'
    | '/examples/basic'
    | '/p/$shareId'
    | '/companies'
    | '/data'
    | '/examples'
    | '/models'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/customize'
    | '/data'
    | '/examples'
    | '/login'
    | '/maps'
    | '/models'
    | '/p'
    | '/projects'
    | '/register'
    | '/companies/$id'
    | '/data/$id'
    | '/examples/3d'
    | '/examples/basic'
    | '/p/$shareId'
    | '/companies/'
    | '/data/'
    | '/examples/'
    | '/models/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  CustomizeRoute: typeof CustomizeRoute
  DataRoute: typeof DataRouteWithChildren
  ExamplesRoute: typeof ExamplesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  PRoute: typeof PRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/examples/': {
      id: '/examples/'
      path: '/'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/data/': {
      id: '/data/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof DataRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/p/$shareId': {
      id: '/p/$shareId'
      path: '/$shareId'
      fullPath: '/p/$shareId'
      preLoaderRoute: typeof PShareIdRouteImport
      parentRoute: typeof PRoute
    }
    '/examples/basic': {
      id: '/examples/basic'
      path: '/basic'
      fullPath: '/examples/basic'
      preLoaderRoute: typeof ExamplesBasicRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/3d': {
      id: '/examples/3d'
      path: '/3d'
      fullPath: '/examples/3d'
      preLoaderRoute: typeof Examples3dRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/data/$id': {
      id: '/data/$id'
      path: '/$id'
      fullPath: '/data/$id'
      preLoaderRoute: typeof DataIdRouteImport
      parentRoute: typeof DataRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface DataRouteChildren {
  DataIdRoute: typeof DataIdRoute
  DataIndexRoute: typeof DataIndexRoute
}

const DataRouteChildren: DataRouteChildren = {
  DataIdRoute: DataIdRoute,
  DataIndexRoute: DataIndexRoute,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

interface ExamplesRouteChildren {
  Examples3dRoute: typeof Examples3dRoute
  ExamplesBasicRoute: typeof ExamplesBasicRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  Examples3dRoute: Examples3dRoute,
  ExamplesBasicRoute: ExamplesBasicRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

interface ModelsRouteChildren {
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface PRouteChildren {
  PShareIdRoute: typeof PShareIdRoute
}

const PRouteChildren: PRouteChildren = {
  PShareIdRoute: PShareIdRoute,
}

const PRouteWithChildren = PRoute._addFileChildren(PRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  CustomizeRoute: CustomizeRoute,
  DataRoute: DataRouteWithChildren,
  ExamplesRoute: ExamplesRouteWithChildren,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  ModelsRoute: ModelsRouteWithChildren,
  PRoute: PRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
