/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MapsRouteImport } from './app/maps'
import { Route as ExamplesRouteImport } from './app/examples'
import { Route as DataRouteImport } from './app/data'
import { Route as IndexRouteImport } from './app/index'
import { Route as ExamplesIndexRouteImport } from './app/examples/index'
import { Route as ExamplesBasicRouteImport } from './app/examples/basic'
import { Route as Examples3dRouteImport } from './app/examples/3d'

const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesRoute,
} as any)
const ExamplesBasicRoute = ExamplesBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => ExamplesRoute,
} as any)
const Examples3dRoute = Examples3dRouteImport.update({
  id: '/3d',
  path: '/3d',
  getParentRoute: () => ExamplesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/maps': typeof MapsRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/maps': typeof MapsRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/examples': typeof ExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/examples': typeof ExamplesRouteWithChildren
  '/maps': typeof MapsRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/examples'
    | '/maps'
    | '/examples/3d'
    | '/examples/basic'
    | '/examples/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/data' | '/maps' | '/examples/3d' | '/examples/basic' | '/examples'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/examples'
    | '/maps'
    | '/examples/3d'
    | '/examples/basic'
    | '/examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  ExamplesRoute: typeof ExamplesRouteWithChildren
  MapsRoute: typeof MapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/basic': {
      id: '/examples/basic'
      path: '/basic'
      fullPath: '/examples/basic'
      preLoaderRoute: typeof ExamplesBasicRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/3d': {
      id: '/examples/3d'
      path: '/3d'
      fullPath: '/examples/3d'
      preLoaderRoute: typeof Examples3dRouteImport
      parentRoute: typeof ExamplesRoute
    }
  }
}

interface ExamplesRouteChildren {
  Examples3dRoute: typeof Examples3dRoute
  ExamplesBasicRoute: typeof ExamplesBasicRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  Examples3dRoute: Examples3dRoute,
  ExamplesBasicRoute: ExamplesBasicRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  ExamplesRoute: ExamplesRouteWithChildren,
  MapsRoute: MapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
