/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MapsRouteImport } from './app/maps'
import { Route as ExamplesRouteImport } from './app/examples'
import { Route as DataRouteImport } from './app/data'
import { Route as CompaniesRouteImport } from './app/companies'
import { Route as IndexRouteImport } from './app/index'
import { Route as ExamplesIndexRouteImport } from './app/examples/index'
import { Route as DataIndexRouteImport } from './app/data/index'
import { Route as CompaniesIndexRouteImport } from './app/companies/index'
import { Route as ExamplesBasicRouteImport } from './app/examples/basic'
import { Route as Examples3dRouteImport } from './app/examples/3d'
import { Route as DataIdRouteImport } from './app/data/$id'
import { Route as CompaniesIdRouteImport } from './app/companies/$id'

const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExamplesRoute,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const ExamplesBasicRoute = ExamplesBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => ExamplesRoute,
} as any)
const Examples3dRoute = Examples3dRouteImport.update({
  id: '/3d',
  path: '/3d',
  getParentRoute: () => ExamplesRoute,
} as any)
const DataIdRoute = DataIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DataRoute,
} as any)
const CompaniesIdRoute = CompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/data': typeof DataRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/maps': typeof MapsRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/data/$id': typeof DataIdRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/companies/': typeof CompaniesIndexRoute
  '/data/': typeof DataIndexRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maps': typeof MapsRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/data/$id': typeof DataIdRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/companies': typeof CompaniesIndexRoute
  '/data': typeof DataIndexRoute
  '/examples': typeof ExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/data': typeof DataRouteWithChildren
  '/examples': typeof ExamplesRouteWithChildren
  '/maps': typeof MapsRoute
  '/companies/$id': typeof CompaniesIdRoute
  '/data/$id': typeof DataIdRoute
  '/examples/3d': typeof Examples3dRoute
  '/examples/basic': typeof ExamplesBasicRoute
  '/companies/': typeof CompaniesIndexRoute
  '/data/': typeof DataIndexRoute
  '/examples/': typeof ExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/data'
    | '/examples'
    | '/maps'
    | '/companies/$id'
    | '/data/$id'
    | '/examples/3d'
    | '/examples/basic'
    | '/companies/'
    | '/data/'
    | '/examples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maps'
    | '/companies/$id'
    | '/data/$id'
    | '/examples/3d'
    | '/examples/basic'
    | '/companies'
    | '/data'
    | '/examples'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/data'
    | '/examples'
    | '/maps'
    | '/companies/$id'
    | '/data/$id'
    | '/examples/3d'
    | '/examples/basic'
    | '/companies/'
    | '/data/'
    | '/examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DataRoute: typeof DataRouteWithChildren
  ExamplesRoute: typeof ExamplesRouteWithChildren
  MapsRoute: typeof MapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/data/': {
      id: '/data/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof DataRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/examples/basic': {
      id: '/examples/basic'
      path: '/basic'
      fullPath: '/examples/basic'
      preLoaderRoute: typeof ExamplesBasicRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/examples/3d': {
      id: '/examples/3d'
      path: '/3d'
      fullPath: '/examples/3d'
      preLoaderRoute: typeof Examples3dRouteImport
      parentRoute: typeof ExamplesRoute
    }
    '/data/$id': {
      id: '/data/$id'
      path: '/$id'
      fullPath: '/data/$id'
      preLoaderRoute: typeof DataIdRouteImport
      parentRoute: typeof DataRoute
    }
    '/companies/$id': {
      id: '/companies/$id'
      path: '/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof CompaniesIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesIdRoute: typeof CompaniesIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesIdRoute: CompaniesIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface DataRouteChildren {
  DataIdRoute: typeof DataIdRoute
  DataIndexRoute: typeof DataIndexRoute
}

const DataRouteChildren: DataRouteChildren = {
  DataIdRoute: DataIdRoute,
  DataIndexRoute: DataIndexRoute,
}

const DataRouteWithChildren = DataRoute._addFileChildren(DataRouteChildren)

interface ExamplesRouteChildren {
  Examples3dRoute: typeof Examples3dRoute
  ExamplesBasicRoute: typeof ExamplesBasicRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

const ExamplesRouteChildren: ExamplesRouteChildren = {
  Examples3dRoute: Examples3dRoute,
  ExamplesBasicRoute: ExamplesBasicRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}

const ExamplesRouteWithChildren = ExamplesRoute._addFileChildren(
  ExamplesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DataRoute: DataRouteWithChildren,
  ExamplesRoute: ExamplesRouteWithChildren,
  MapsRoute: MapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
